# ========================================================================== #
#   _    _                        __  __                                     #
#  | |  | |                      |  \/  |                                    #
#  | |__| | ___  _ __ ___   ___  | \  / | __ _ _ __   __ _  __ _  ___ _ __   #
#  |  __  |/ _ \| '_ ` _ \ / _ \ | |\/| |/ _` | '_ \ / _` |/ _` |/ _ \ '__|  #
#  | |  | | (_) | | | | | |  __/ | |  | | (_| | | | | (_| | (_| |  __/ |     #
#  |_|  |_|\___/|_| |_| |_|\___| |_|  |_|\__,_|_| |_|\__,_|\__, |\___|_|     #
#                                                           __/ |            #
#                                                          |___/             #
# ========================================================================== #

debug:
  # Enables debug logging.
  logging: true

# Duration in seconds for how long cached data remains valid.
# Data is automatically invalidated when creating or deleting homes.
# Cached data is only used for tab completion.
cacheExpireDuration: 600

# Duration of the visual highlight in seconds when using the /homesearch command.
homeSearchDurationInSeconds: 30

# Time in seconds an admin has to confirm an action,
# such as purging all homes in a world.
homeAdminConfirmationDuration: 5

# The regex used to validate a home name.
# If the name does not match the regex, the commands.sethome.invalidName lang key is returned
validHomeNameRegex: "[A-Za-z0-9-_]{0,30}"