debug:
  logging: true
  regenerateConfigsOnStart: true

# Duration is ms (100000ms => 100s)
tabCompletionCacheExpireDuration: 100000

homeSearchDurationInSeconds: 30

homeAdminConfirmationDuration: 10