name: HomeManager
version: '${project.version}'
main: me.hasenzahn1.homemanager.HomeManager
api-version: '1.21'
authors: [ Hasenzahn1 ]
description: A Plugin for managing homes in a customizable way

commands:
  sethome:
    description: Sets a home at your position
    usage: /sethome (player) name